export const rickAndMortyQuotes = {
    1: "Wubba Lubba Dub Dub!  — Rick",
    2: "What, so everyone`s supposed to sleep every single night now? You realize that nighttime makes up half of all time?  — Rick",
    3: "Boom! Big reveal! I turned myself into a pickle! — Rick",
    4: "Nobody exists on purpose. Nobody belongs anywhere. We`re all going to die. Come watch TV.  — Morty",
    5: "To live is to risk it all; otherwise you`re just an inert chunk of randomly assembled molecules drifting wherever the universe blows you.  — Rick",
    6: "Weddings are basically funerals with a cake.  — Rick",
    7: "I`ll tell you how I feel about school, Jerry: It`s a waste of time. Bunch of people runnin` around bumpin` into each other, got a guy up front says, Two plus two, and the people in the back say, Four. Then the bell rings and they give you a carton of milk and a piece of paper that says you can go take a dump or somethin`. I mean, it`s not a place for smart people, Jerry. I know that`s not a popular opinion, but that`s my two cents on the issue.  — Rick",
    8: "Sometimes science is more art than science.  — Rick",
    9: "If I let you make me nervous, then we can`t get schwifty.  — Rick",
    10: "Listen, Morty, I hate to break it to you, but what people call love is just a chemical reaction that compels animals to breed.  — Rick",
    11: "Don`t move. Gonorrhea can`t see us if we don`t move. Wait! I was wrong! I was thinking of a T. rex.  — Rick",
    12: "Excuse me. Coming through. What are you here for? Just kidding, I don`t care.  — Rick",
    13: "Listen, I`m not the nicest guy in the universe, because I`m the smartest, and being nice is something stupid people do to hedge their bets.  — Rick",
    14: "I know that new situations can be intimidating. You`re lookin` around and it`s all scary and different, but y`know, meeting them head-on, charging into 'em like a bull  — that`s how we grow as people. — Rick",
    15: "You gotta do it for Grandpa, Morty. You gotta put these seeds inside your butt.  — Rick",
    16: "Morty, I need your help on an adventure. Eh, need is a strong word. We need door stops, but a brick would work too.  — Rick",
    17: "I`m a scientist; because I invent, transform, create, and destroy for a living, and when I don`t like something about the world, I change it.  — Pickle Rick",
    18: "He`s not a hot girl. He can`t just bail on his life and set up shop in someone else`s.  — Beth",
    19: "Honey, stop raising your father`s cholesterol so you can take a hot funeral selfie.  — Beth",
    20: "So what if he`s the devil, Rick? At least the devil has a job. At least he`s active in the community.  — Summer",
    21: "So I have an emo streak. It`s part of what makes me so rad.  — Rick",
    22: "I just want to go back to hell, where everyone thinks I`m smart and funny.  — Mr. Needful",
    23: "Don`t deify the people who leave you.  — Beth",
    24: "If I die in a cage, I lose a bet.  — Rick",
    25: "Yeah, sure, I mean, if you spend all day shuffling words around, you can make anything sound bad, Morty.  — Rick",
    26: "Don`t get drawn into the culture, Morty. Stealing stuff is about the stuff, not the stealing.  — Rick",
    27: "To live is to risk it all—otherwise, you're just an inert chunk of randomly assembled molecules drifting wherever the universe blows you.  — Rick",
    28: "I`m sorry, but your opinion means very little to me.  — Rick",
    29: "Hi Mr. Jellybean, I`m Morty. I`m on an adventure with my grandpa.  — Morty",
    30: "B*tch, my generation gets traumatized for breakfast!  — Summer",
    31: "You`re the little brother. You`re not the cause of your parents` misery, you`re just a symptom of it.  — Summer",
    32: "Having a family doesn`t mean that you stop being an individual. You know the best thing you can do for the people that depend on you? Be honest with them, even if it means setting them free.  — Mr. Meeseeks",
    33: "Well then get your shit together, get it all together and put it in a backpack, all your shit, so it`s together. And if you gotta take it somewhere, take it somewhere, you know. Take it to the shit store and sell it, or put it in the shit museum. I don`t care what you do, you just gotta get it together. Get your shit together.  — Morty",
    34: "I don`t like it here, Morty. I can`t abide bureaucracy. I don`t like being told where to go and what to do. I consider it a violation. Did you get those seeds all the way up your butt?  — Rick",
    35: "Hey, muchacho, does your planet have wiper fluid yet or you gonna freak out and start worshipping us?  — Rick",
    36: "It`s funny to say they are small. It`s funny to say they are big.  — Shrimply Pibbles",
    37: "Listen, Morty, I hate to break it to you, but what people call love is just a chemical reaction that compels animals to breed. It hits hard, Morty, then it slowly fades, leaving you stranded in a failing marriage. I did it. Your parents are gonna do it. Break the cycle, Morty. Rise above. Focus on science.  — Rick",
    38: "This pickle doesn`t care about your children. I`m not gonna take their dreams. I`m gonna take their parents.  — Rick",
    39: "Life is effort and I`ll stop when I die!  — Jerry"
}
